{\rtf1\ansi\ansicpg1252\cocoartf1671\cocoasubrtf600
{\fonttbl\f0\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl280\partightenfactor0

\f0\fs24 \cf2 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 \{"swagger":"2.0","info":\{"description":"Api Documentation","version":"1.0","title":"Api Documentation","termsOfService":"urn:tos","contact":\{\},"license":\{"name":"Apache 2.0","url":"http://www.apache.org/licenses/LICENSE-2.0"\}\},"host":"crud-evals15-tutoria-2257.apps.logistic-14f6.open.redhat.com","basePath":"/","tags":[\{"name":"fruit-controller","description":"Fruit Controller"\}],"paths":\{"/api/fruits":\{"get":\{"tags":["fruit-controller"],"summary":"Get All Fruits","operationId":"getAllUsingGET","produces":["*/*"],"responses":\{"200":\{"description":"OK","schema":\{"type":"array","items":\{"$ref":"#/definitions/Fruit"\}\}\},"401":\{"description":"Unauthorized"\},"403":\{"description":"Forbidden"\},"404":\{"description":"Not Found"\}\},"deprecated":false\},"post":\{"tags":["fruit-controller"],"summary":"Create a fruit","operationId":"postUsingPOST","consumes":["application/json"],"produces":["*/*"],"parameters":[\{"in":"body","name":"fruit","description":"fruit","required":false,"schema":\{"$ref":"#/definitions/Fruit"\}\}],"responses":\{"201":\{"description":"Created","schema":\{"$ref":"#/definitions/Fruit"\}\},"401":\{"description":"Unauthorized"\},"403":\{"description":"Forbidden"\},"404":\{"description":"Not Found"\}\},"deprecated":false\}\},"/api/fruits/\{id\}":\{"put":\{"tags":["fruit-controller"],"summary":"Update a fruit","operationId":"putUsingPUT","consumes":["application/json"],"produces":["*/*"],"parameters":[\{"in":"body","name":"fruit","description":"fruit","required":false,"schema":\{"$ref":"#/definitions/Fruit"\}\},\{"name":"id","in":"path","description":"id","required":true,"type":"integer","format":"int32"\}],"responses":\{"200":\{"description":"OK","schema":\{"$ref":"#/definitions/Fruit"\}\},"201":\{"description":"Created"\},"401":\{"description":"Unauthorized"\},"403":\{"description":"Forbidden"\},"404":\{"description":"Not Found"\}\},"deprecated":false\},"delete":\{"tags":["fruit-controller"],"summary":"Delete a fruit","operationId":"deleteUsingDELETE","produces":["*/*"],"parameters":[\{"name":"id","in":"path","description":"id","required":true,"type":"integer","format":"int32"\}],"responses":\{"204":\{"description":"No Content"\},"401":\{"description":"Unauthorized"\},"403":\{"description":"Forbidden"\}\},"deprecated":false\}\}\},"definitions":\{"Fruit":\{"type":"object","properties":\{"id":\{"type":"integer","format":"int32"\},"name":\{"type":"string"\}\},"title":"Fruit"\}\}\}\
}